### ISSUE TITLE
Generate python==3.9, egl version of vtk wheel

### ISSUE THREAD

**Issue by joserand** [banesullivan/vtk-cmake#2]
Hi, because I am a newbie, I currently want to generate other python versions and vtk wheels based on egl versions, I would like to confirm with you whether the following modifications based on the dockerfile in the original code are correct, thank you very much for your reply

    FROM python:3.9 as builder
    
    RUN mkdir -p /app
    COPY ./cmake/ /app/cmake/
    COPY ./scripts/ /app/scripts/
    WORKDIR /app
    
    RUN ./scripts/install.sh
    
    ARG VTK_VERSION=9.2.6
    ARG VTK_VARIANT="egl"
    RUN VTK_VERSION=${VTK_VERSION} VTK_VARIANT=${VTK_VARIANT} ./scripts/build.sh
    
    ############################################
    ARG PYTHON_VERSION=3.9
    FROM python:3.9-slim
    RUN mkdir -p opt/vtk/
    COPY --from=builder /app/vtk/build/dist/*.whl /opt/vtk/
    
    RUN apt update && apt install -y libosmesa6 && rm -rf /var/lib/apt/lists/*
    
    RUN pip install /opt/vtk/*.whl
    
    # Validate installation
    RUN python -c "import vtk; print(vtk.VTK_VERSION)"

**Comment by joserand** [comment]
Of course, I need the GPU version of Pyvista, so I also modified the dockerfile that generated the GPU version of PyVista (not for jupyter), please can you help me confirm if my changes are correct？

    FROM python:3.9
    LABEL maintainer="PyVista Developers"
    LABEL repo="https://github.com/pyvista/pyvista"
    
    USER root
    RUN apt-get update \
        && apt-get install -y -qq --no-install-recommends \
            libopengl0 \
            libglvnd0 \
            libgl1 \
            libglx0 \
            libegl1 \
        && rm -rf /var/lib/apt/lists/*
    USER jovyan
    
    COPY vtk-9.2.6.post0+egl-cp39-cp39-linux_x86_64.whl /build-context/
    WORKDIR /build-context/
    
    RUN pip install --no-cache-dir vtk*.whl
    RUN pip install pyvista
    # https://github.com/Kitware/trame-vtk/issues/55
    RUN pip install 'aiohttp<3.9'
    
    WORKDIR $HOME
    
    ENV NVIDIA_VISIBLE_DEVICES all
    ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
    ENV JUPYTER_ENABLE_LAB=yes
    ENV PYVISTA_TRAME_SERVER_PROXY_PREFIX='/proxy/'
    
    COPY *.ipynb $HOME/
In my vision, my python code is as follows

    import pyvista as pv
    from pyvista import examples
    pv.set_jupyter_backend('server')
    pv.Report()
    vol = examples.download_head_2()
    pl = pv.Plotter()
    pl.add_volume(vol)
    pl.show()

Thank you again for your help

**Comment by banesullivan** [comment]
generally I think this looks good and should do it! Though there may be some problems with my scripts in here in setting `VTK_VARIANT`. I'll double check things shortly here and if I have a moment will try to make it so that the Python version can be specified as a build argument

**Comment by banesullivan** [comment]
Update: I'm going to push some changes to the repository shortly as I was missing the build dependencies for EGL

**Comment by joserand** [comment]
This sounds fantastic, looking forward to your update

**Comment by banesullivan** [comment]
My latest changes on `main` from commit 6421bd8 improve all of this! Now all you'd need to do is clone the repository and run:

```bash
# Build VTK 9.3 with EGL on Python 3.9
docker build --target slim --build-arg='PYTHON_VERSION=3.9' --build-arg='VTK_VERSION=9.2.6' --build-arg='VTK_VARIANT=egl' -t vtk-python .
```

And if you want PyVista/Jupyter:

```bash
# Build VTK 9.3 with EGL on Python 3.9 with Jupyter+PyVista
docker build --target jupyter --build-arg='PYTHON_VERSION=3.9' --build-arg='VTK_VERSION=9.2.6' --build-arg='VTK_VARIANT=egl' -t pyvista-gpu .
```

Let me know how that goes!

**Comment by banesullivan** [comment]
Hm. I say that, but the build just failed locally for me with Python 3.9

**Comment by banesullivan** [comment]
Using `VTK_VERSION=9.2.6` might be better for Python 3.9

**Comment by banesullivan** [comment]
Confirmed for me that VTK `9.2.6` has no issues on Python 3.9. The latest VTK (9.3.0) is having issues in this build set up with Python 3.9

**Comment by banesullivan** [comment]
@joserand, let me know if you have any issue getting this to work, but it should be good to go. I've built this image and pushed to the container registry for this repo as `ghcr.io/banesullivan/pyvista-gpu:3.9-9.2.6` You should be able to:

```bash
docker pull ghcr.io/banesullivan/pyvista-gpu:3.9-9.2.6
docker run -it -p 8888:8888 --rm --runtime=nvidia --gpus all ghcr.io/banesullivan/pyvista-gpu:3.9-9.2.6
```

Or build yourself after cloning this repo:
```
docker build --target jupyter --build-arg='PYTHON_VERSION=3.9' --build-arg='VTK_VERSION=9.2.6' --build-arg='VTK_VARIANT=egl' -t ghcr.io/banesullivan/pyvista-gpu:3.9-9.2.6 .

docker run -it -p 8888:8888 --rm --runtime=nvidia --gpus all ghcr.io/banesullivan/pyvista-gpu:3.9-9.2.6
```

**Comment by joserand** [comment]
I'm sorry I didn't have time to reply to your message until now and kept you waiting so long. 
Last week I had to prepare for a very important exam, and now I'm still preparing for the exam. Around this Friday, I'll have time to try it out. 
Thanks for your reply. I'll get back to you as soon as I'm done trying, regardless of whether I can finish building the vtk-egl version locally based on your code.

**Comment by joserand** [comment]
I've tried your reply and I've now been able to build a *python==3.9*, *vtk==9.2.6* version of the vtk.I can also generate the corresponding pyvista-gpu. Thank you very much.
In order to use the GPU version of PyVista in my current campaign, I did a little bit of research into the code. I found that the pyvista part doesn't seem to change, the different vtk versions lead to different pyvista. I'm not quite sure if I'm right. Because in my subsequent activities, I just installed the generated whl . 

    pip install aiohttp==3.9.1
    pip install trame
    pip install trame-vtk
    pip install trame-vuetify 
    pip install matplotlib 
    pip install /deploy/config_update/*.whl

But there seems to be a partial problem with the vtk call:

    023-12-07 10:12:42.496 (   0.181s) [         BE0E740]   vtkShaderProgram.cxx:452    ERR| vtkShaderProgram (0x2e5e6e0): 1: 
    2:   #version 140
    3: #ifdef GL_ES
    4: #ifdef GL_FRAGMENT_PRECISION_HIGH
    5: precision highp float;
    6: precision highp sampler2D;
    7: precision highp sampler3D;
    8: #else
    9: precision mediump float;
    10: precision mediump sampler2D;
    11: precision mediump sampler3D;
    12: #endif
    13: #define texelFetchBuffer texelFetch
    14: #define texture1D texture
    15: #define texture2D texture
    16: #define texture3D texture
    17: #else // GL_ES
    18: #define highp
    19: #define mediump
    20: #define lowp
    21: #if __VERSION__ == 150
    22: #define texelFetchBuffer texelFetch
    23: #define texture1D texture
    24: #define texture2D texture
    25: #define texture3D texture
    26: #endif
    27: #endif // GL_ES
    28: #define varying in
    29: 
    30:   in vec2 texCoord;
    31:   uniform sampler2DMS tex;
    32:   uniform int samplecount;
    33:   out vec4 fragOutput0;
    34: 
    35: 
    36:   void main()
    37:   {
    38:     float gamma = 2.2;
    39: 
    40:     // for each sample in the multi sample buffer...
    41:     ivec2 itexcoords = ivec2(floor(textureSize(tex) * texCoord));
    42:     vec3 accumulate = vec3(0.0,0.0,0.0);
    43:     float alpha = 0.0;
    44: 
    45:     for (int i = 0; i < samplecount; i++)
    46:     {
    47:       vec4 sample = texelFetch(tex, itexcoords, i);
    48:       // apply gamma correction and sum
    49:       accumulate += pow(sample.rgb, vec3(gamma));
    50:       alpha += sample.a;
    51:     }
    52: 
    53:     // divide and reverse gamma correction
    54:     accumulate /= float(samplecount);
    55:     fragOutput0 = vec4(pow(accumulate, vec3(1.0/gamma)), alpha/float(samplecount));
    56:   }
    57:   
    
    2023-12-07 10:12:42.496 (   0.181s) [         BE0E740]   vtkShaderProgram.cxx:453    ERR| vtkShaderProgram (0x2e5e6e0): 0:31(22): error: syntax error, unexpected NEW_IDENTIFIER, expecting '{'
    
    2023-12-07 10:12:42.496 (   0.181s) [         BE0E740]vtkOpenGLVertexArrayObj:265    ERR| vtkOpenGLVertexArrayObject (0x2cfc4f0): attempt to add attribute without a program for attribute ndCoordIn
    2023-12-07 10:12:42.496 (   0.181s) [         BE0E740]vtkOpenGLQuadHelper.cxx:70    WARN| Error binding ndCoords to VAO.
    2023-12-07 10:12:42.496 (   0.182s) [         BE0E740]vtkOpenGLRenderWindow.c:1099   ERR| vtkEGLRenderWindow (0x20cec50): Couldn't build the shader program for resolving msaa.
    Traceback (most recent call last):
      File "/deploy/app.py", line 91, in <module>
        view = vtk_widgets.VtkRemoteView(
      File "/deploy/server/venv/lib/python3.9/site-packages/trame_vtk/widgets/vtk/common.py", line 685, in __init__
        MODULE.has_capabilities("web", "rendering")
      File "/deploy/server/venv/lib/python3.9/site-packages/trame_vtk/modules/vtk/__init__.py", line 32, in has_capabilities
        raise ImportError(IMPROPER_VTK_MSG)
    ImportError: Your build of VTK does not have the proper web modules enabled.
    These modules are typically enabled by default with the
    `-DVTK_GROUP_ENABLE_Web:STRING=WANT` build flag.
    
    Conda users: This is a known issue with the conda-forge VTK feedstock.
    See https://github.com/conda-forge/vtk-feedstock/pull/258

The last line of the error gives a possible solution path, and I will try to solve it tomorrow when I have time.

**Comment by banesullivan** [comment]
Hmm, I want to make sure you didn't have pyvista installed previously. You may need to install the custom vtk wheel before anything else

**Comment by joserand** [comment]
I seem to get it.I installed vtk after installing pyvsita. I'll try your suggestions today. And  after trying, I'll reply to you the results . Thanks you very much!!!!!!!!!!!!!!!!!!!!!

**Comment by joserand** [comment]
I'm still getting errors. And due to the requirements of the APT environment of the vtk-egl version created, I need to download the corresponding package again in the new image.  It feels like a bit of a waste of time. I've decided to think differently - I'll start with the pyvista-gpu image to finish work and I'll reply to you the results next week. Have a good weekend.

**Comment by joserand** [comment]
Recently, I built a multi-user Pyvista web presentation on my own. Based on your image code, my code is deployed in a container. Thank you very much for the code and the answers, I successfully built the vtk-gpu version and showed my model in linux.
Thank youuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu!
