### ISSUE TITLE
NVIDIA GeForce 4090 can not support egl-vtk

### ISSUE THREAD

**Issue by Grople** [banesullivan/vtk-cmake#3]
**Question describe:**
since I am the newbie,I pull the docker image from your hub docker pull ghcr.io/banesullivan/pyvista-gpu:3.9-9.2.6, and then I test it on three device, titan xp, NVIDIA GeForce 3080, and NVIDIA GeForce 4090, but only the **device 4090 can not work with GPU to render**, could you tell me the reason? thank you very much!!

**Comment by banesullivan** [comment]
Huh that is very odd indeed. I have an NVIDIA GeForce 3080 that I'm using locally. Are these all on the same machine? I wonder if a graphics driver is missing for the 4090 set up... 

Can you use the 4090 GPU for other graphics task outside of docker?

**Comment by Grople** [comment]
I test it on three different machine, each machine installed the cuda driver，and they all can run the deep learning model inside the docker, however, only 4090 GPU can not render.

**Comment by Grople** [comment]
just now, I test it on a new machine 3090 GPU, only installed cuda driver and docker, it is also can not work, now I am looking for problem.

**Comment by Grople** [comment]
hello, I do a lot of experiences including wsl2(3060, **can not work**), two 4090 GPU **(one could work, another one can not work)**, one 3090 GPU (can not work) , one 3080 GPU (work), and titan xp (work), and each GPU on a different machine, so I guess the problem maybe lack a sofaware package,  which need to apt or apt-get install it, but now I don't know lack which packages.

**Comment by Grople** [comment]
I solved the problem by installing vulkan package and cuda driver on dockerfile **./CUDA_DRIVER.run -s --no-module**. I think this phenomenon caused by docker engine version, the simplest way to solve it is upgrade docker engine.

**Comment by banesullivan** [comment]
Fantastic, glad you were able to solve this and I appreciate you sharing the solution for others to see
